openapi:
  title: DLlama API
  version: 1.0.0
  description: API for a an LLM service using Dart and Avarex Llama
  enable: true

aiModels:
  llm: "granite-3.3-2b-instruct-Q5_1.gguf"

server:
  port: 8080
  host: localhost

env:
  mode: debug

